services:
  - type: web
    name: gharsathi
    env: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_APP_URL
        value: https://gharsathi.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: AUTH_SECRET
        generateValue: true
